version: 1.2.1.{build}
image: Visual Studio 2017


environment:
  matrix:
    - PlatformToolset: v140_xp
    - PlatformToolset: v141_xp

platform:
    - x64
    - x86

configuration:
    - Release
    - Debug


install:
    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="x64" set platform_input=x64

    - if "%platform%"=="x86" set archi=x86
    - if "%platform%"=="x86" set platform_input=x86

    - if "%PlatformToolset%"=="v140_xp" call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %archi%
    - if "%PlatformToolset%"=="v141_xp" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %archi%


build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - msbuild PyNPP.sln /m /p:configuration="%configuration%" /p:platform="%platform_input%" /p:PlatformToolset="%PlatformToolset%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - ps: >-

        if ($env:PLATFORM_INPUT -eq "x64") {
            Push-AppveyorArtifact "$env:PLATFORM_INPUT\$env:CONFIGURATION\PyNPP.dll" -FileName PyNPP.dll
        }

        if ($env:PLATFORM_INPUT -eq "x86" ) {
            Push-AppveyorArtifact "$env:CONFIGURATION\PyNPP.dll" -FileName PyNPP.dll
        }

        if ($($env:APPVEYOR_REPO_TAG) -eq "true" -and $env:CONFIGURATION -eq "Release" -and $env:PLATFORMTOOLSET -eq "v140_xp") {
            if($env:PLATFORM_INPUT -eq "x64"){
            $ZipFileName = "PyNPP_$($env:APPVEYOR_REPO_TAG_NAME)_x64.zip"
            7z a $ZipFileName $env:PLATFORM_INPUT\$env:CONFIGURATION\PyNPP.dll
            }
            if($env:PLATFORM_INPUT -eq "x86"){
            $ZipFileName = "PyNPP_$($env:APPVEYOR_REPO_TAG_NAME)_x86.zip"
            7z a $ZipFileName $env:CONFIGURATION\PyNPP.dll
            }
        }

artifacts:
  - path: PyNPP_*.zip
    name: releases

deploy:
    provider: GitHub
    auth_token:
        secure: hae5XZIpQjSn848JxWI23HJmL2AWTkptyKwZDZreQsJLQplXpcUGSIr0SGA1q6s0
    artifact: releases
    draft: false
    prerelease: false
    force_update: true
    on:
        appveyor_repo_tag: true
        PlatformToolset: v140_xp
        configuration: Release
